version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/achimonchi/CircleCi
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: make test
      - run: go version